<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Default test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="0.000">
    <properties></properties>

            <testcase
                name="testDataDriven"
                time="0.000"
                classname="ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario">

            <failure type="java.lang.RuntimeException" message="java.nio.file.InvalidPathException: Illegal char &lt;:&gt; at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx">
                <![CDATA[java.lang.RuntimeException: java.nio.file.InvalidPathException: Illegal char <:> at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx
                org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:58)org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)org.testng.internal.Parameters.handleParameters(Parameters.java:809)org.testng.internal.Parameters.handleParameters(Parameters.java:734)org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1596)org.testng.TestRunner.privateRun(TestRunner.java:739)org.testng.TestRunner.run(TestRunner.java:614)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
                    Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 33: E:\ABTB6x\LearningSeleniumATB6x\E:\ABTB6x\LearningSeleniumATB6x\resources\TataData.xlsx
                    java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:204)java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:175)java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:231)java.base/java.io.File.toPath(File.java:2401)org.apache.poi.openxml4j.opc.ZipPackage.openZipEntrySourceStream(ZipPackage.java:209)org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:199)org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:171)org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:247)org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:179)org.apache.poi.ooxml.POIXMLDocument.openPackage(POIXMLDocument.java:88)org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:358)ex_Selenium_DataDrivenTesting.ExcelReader.getDataFromSheet(ExcelReader.java:139)ex_Selenium_DataDrivenTesting.DDT_RealTimeScenario.testDataExcel(DDT_RealTimeScenario.java:65)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)java.base/java.lang.reflect.Method.invoke(Method.java:580)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)org.testng.internal.invokers.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:54)org.testng.internal.invokers.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:159)org.testng.internal.Parameters.handleParameters(Parameters.java:809)org.testng.internal.Parameters.handleParameters(Parameters.java:734)org.testng.internal.invokers.ParameterHandler.handleParameters(ParameterHandler.java:72)org.testng.internal.invokers.ParameterHandler.createParameters(ParameterHandler.java:51)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:946)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)java.base/java.util.ArrayList.forEach(ArrayList.java:1596)org.testng.TestRunner.privateRun(TestRunner.java:739)org.testng.TestRunner.run(TestRunner.java:614)org.testng.SuiteRunner.runTest(SuiteRunner.java:421)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)org.testng.SuiteRunner.run(SuiteRunner.java:312)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)org.testng.TestNG.runSuitesLocally(TestNG.java:1208)org.testng.TestNG.runSuites(TestNG.java:1112)org.testng.TestNG.run(TestNG.java:1079)org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
                ]]>
            </failure>
    </testcase>


</testsuite>
